project_id = "qkinpgrvvsxtepmbcwzk"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.create-checkout]
    verify_jwt = false
  [functions.payments-webhook]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.test-course-email]
    verify_jwt = false
